name: liquid_pose
channels:
  -pytorch
  -nvidia
  -defaults
dependencies:
  -python=3.9
  -pytorch >= 1.13.0
  -torchvision >= 0.14.0
  -pytorch-cuda=11.7
  -numpy>=1.21
  -pandas
  -scipy
  -matplotlib
  -tqdm
  -pip
  -pip:
    -opencv-python
    -smplx